name: Mail Notify ([notify] commits)
on: push
jobs:
  mail-tag:
    uses: zeppe-lin/.github-shared-workflows/.github/workflows/notify-mail-tag.yml@master
    with:
      mail_to: zeppe-lin@freelists.org
    secrets:
      smtp_user: ${{ secrets.GMAIL_USERNAME }}
      smtp_pass: ${{ secrets.GMAIL_APP_PASSWORD }}

